services:
  redis:
    container_name: lunchmenu-redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --loglevel warning"
    volumes:
      - "redis_data:/data"
    extra_hosts:
      - host.docker.internal:host-gateway

  lunchmenu:
    container_name: lunchmenu
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data:
