# For local development, only database is running
#
# docker compose up -d
# fastapi dev
#
services:
  redis:
    container_name: lunchmenu-redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --loglevel warning"
    volumes:
      - "redis_data:/data"
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  redis_data:
